# Example of custom Java runtime using jlink in a multi-stage container build
FROM eclipse-temurin:11-jdk
# as jre-build
#
## Create a custom Java runtime
#RUN $JAVA_HOME/bin/jlink \
#         --add-modules java.base \
#         --strip-debug \
#         --no-man-pages \
#         --no-header-files \
#         --compress=2 \
#         --output /javaruntime
#
## Define your base image
#FROM debian:buster-slim
#ENV JAVA_HOME=/opt/java/openjdk
#ENV PATH "${JAVA_HOME}/bin:${PATH}"
#COPY --from=jre-build /javaruntime $JAVA_HOME


EXPOSE 8080:8080
ADD build/libs/app-spring-boot-version-lambda.war /app/
WORKDIR /app
CMD ["java", "-jar", "app-spring-boot-version-lambda.war"]
